=== DJDims/XML/01_Materials/xml_python/movies.dtd
<!ELEMENT Movies (Movie+)>
<!ELEMENT Movie (Title,Genres,Director,Actors,Studio,Year)>
<!ATTLIST Movie rating NMTOKEN #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title runtime NMTOKEN #REQUIRED>
<!ELEMENT Genres (Genre+)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT Director (Name)>
<!ELEMENT Name (First,Last)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Last (#PCDATA)>
<!ELEMENT Actors (Actor+)>
<!ELEMENT Actor (#PCDATA)>
<!ELEMENT Studio (#PCDATA)>
<!ELEMENT Year (#PCDATA)>

=== DJDims/XML/01_Materials/xml_python/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE Movies SYSTEM "movies.dtd"> -->
<?xml-model href="movies.xsd"?>
<Movies>
    <Movie rating="R">
        <Title runtime="177">The Godfather</Title>
        <Genres>
            <Genre>Crime</Genre>
            <Genre>Drama</Genre>
        </Genres>
        <Director>
            <Name>
                <First>Francis Ford</First>
                <Last>Coppola</Last>
            </Name>
        </Director>
        <Actors>
            <Actor>Marlon Brando</Actor>
            <Actor>Al Pacino</Actor>
            <Actor>James Caan</Actor>
        </Actors>
        <Studio>Paramount Pictures</Studio>
        <Year>1972</Year>
    </Movie>
    <Movie rating="R">
        <Title runtime="194">Titanic</Title>
        <Genres>
            <Genre>Drama</Genre>
        </Genres>
        <Director>
            <Name>
                <First>James</First>
                <Last>Cameron</Last>
            </Name>
        </Director>
        <Actors>
            <Actor>Leonardo DiCaprio</Actor>
            <Actor>Kate Winslet</Actor>
            <Actor>Billy Zane</Actor>
        </Actors>
        <Studio>Paramount Pictures</Studio>
        <Year>1997</Year>
    </Movie>
</Movies>
